### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by EmmanuelBeziat** [EmmanuelBeziat/emmanuelbeziat#1]
# Core
- [x] Convert markdown posts in Json files
  - [x] Video embedding (https://github.com/rotorz/markdown-it-block-embed)
  - [x] Custom classes and attributes (https://github.com/arve0/markdown-it-attrs)
  - [ ] Add ID and anchor on titles (https://github.com/valeriangalliat/markdown-it-anchor)
- [x] List posts or show single one
- [ ] Tags / categories support (archives system)
- [ ] Paging system (next post / previous post, etc.) (https://github.com/TahaSh/vue-paginate)
- [ ] Performance optimization ?
-  ~~Tweets from my account with #blog or #portfolio tag~~ Impossible in plain JS
- [x] Seo ([vue-head](https://github.com/ktquez/vue-head)) for posts / social shares
  - [ ] Short urls
- [ ] Put favicons in static
- [ ] Svg Sprites
  - [x] Generate sprites on run
  - [ ] Load svg from assets
- [ ] Search field
- [x] Smooth scroll for anchors (https://github.com/cferdinandi/smooth-scroll)
- [x] Show only posts when date is past
- [x] RSS feed
# Style
- [x] Main layout
- [x] Blog posts
- [x] Syntax hihglight ([PrismJS](https://github.com/PrismJS/prism))
- [x] Showcase posts
- [x] Responsive all the things!
# Content
- [x] Convert all blog posts from WP to Markdown
- [x] Get all images back from WP
- [x] Showcase posts
- [x] Home
- [ ] Projects
# Server related
- [x] Host on Github Pages
- [x] Generate ssl for https url
# Scripts
- [x] Create new posts from cli
- [x] Automatically push `dist/` folder to `gh-pages` branch
  - [x] Allow custom message
- [ ] Deploy with Travis-CI
# Maybe later ?
- [x] Add Disqus ([Vue-Disqus](https://github.com/ktquez/vue-disqus))
- [x] Evaluate if better convert markdown to json or render markdown in app
- [ ] Migrate to vue2 (https://github.com/vuejs/vue-migration-helper/)

---

Stolen this roadmap idea from [reverland](https://github.com/reverland/), thanks!

**Comment by EmmanuelBeziat** [comment]
Website is online.

Just added a post-maker cli script.

Need to check ou Travis-CI for continuous integration and automatically push `dist/` folder in `gh-pages` branch

**Comment by simmstein** [comment]
Have you planned a RSS feed?

**Comment by EmmanuelBeziat** [comment]
@simmstein Probably. I think about it, but I'm not sure if it would be a great feature… In fact, I never really used RSS feeds myself, and I don't know if how much it's popular. Google and Facebook dropped their RSS readers.

But I'm adding this to the list.

**Comment by simmstein** [comment]
I followed you with it :) Thanks.

**Comment by reverland** [comment]
I've implemented a simple rss plugin...really simple but may useful

**Comment by EmmanuelBeziat** [comment]
@reverland Thanks! I already checked how you did yours. I was a bit uncertain about using ejs, but I'll follow your work (again! 😄 ) on this.

**Comment by reverland** [comment]
@EmmanuelBeziat Jade is ok, or any other template language may work, it just a function provided by html-webpack-plugin

**Comment by EmmanuelBeziat** [comment]
@reverland thanks for the tip; I‘ll try to use Pug on this, but for now I‘ll stick to your example with ejs, until I get it to work. 😄

**Comment by EmmanuelBeziat** [comment]
RSS feed is done (with a strange bug, but working anyway). Thanks again reverland. :)

**Comment by EmmanuelBeziat** [comment]
Also, meta tags are updated to match current page title, opengraph, etc.

**Comment by EmmanuelBeziat** [comment]
Maybe switch to vue2 some day… but there‘s a bit of work.

https://github.com/vuejs/vue-migration-helper/ help

**Comment by EmmanuelBeziat** [comment]
If in need of a mailform: https://formspree.io/

**Comment by reverland** [comment]
@EmmanuelBeziat Yeah, I know this project when its 1.0 https://github.com/viko16/vue-ghpages-blog , it uses github's several api to render markdown and so on, interesting

**Comment by EmmanuelBeziat** [comment]
Has beed updated to vueJS 2, but without special changes in the core. So roadmap v2 is still running.
